### ISSUE TITLE
[HP Printer] HP LaserJet 200 color M251nw printer issues

### ISSUE THREAD

**Issue by h4lloween** [Cossey/openhab2-addons#15]
Hi,

I have the following issues with this printer and the latest binding version:

1) Autodiscovery works - but the printer is detected as "unsupported"
The discovery result shows as 
```
HP LaserJet 200 color M251nw (28465B)
Unsupported HP Printer
```
and some channels are missing (page counts, etc.)

2) Adding the printer manually also does not work, the status always stays at
```
Status: UNKNOWN 
```

**Comment by Cossey** [comment]
Thanks heaps for raising this issue! The information you have provided is _very helpful!_

I was not sure how this printer identified itself over UPNP (hence its mention under possible issues on the community post) it seems I got this incorrect therefore it identifies as unsupported HP printer since it doesn’t match the name check. I can change this and get it correctly identified and picked up by the system. 

**Note: The unsupported HP thing supports the status and ink/toner level channels only; this is by design.**

_The issue of manually adding the Thing and it showing as offline is one I’ve haven’t come across in my testing; I know why it happens so I’ll get that fixed up._

**Comment by Cossey** [comment]
Fixed mentioned issues above, if the problem still persists, please comment here and I will re-open the issue.
